Ff buttons fix
PyLatam/2019-website pull request #9
Opened 2019-04-05 22:54 UTC by cyraxjoe

Rather _dirty_ fix for the problem with unresponsive buttons for firefox in the dashboard. 

Also... download the background image used in the dashboard. I see no reason to download it from the other server. But correct me if I'm wrong.

2019-04-10 22:45 UTC, czpython requested changes

2019-04-10 22:45 UTC, czpython commented on static/css/dashboard.css
> +  background-image:url('/static/img/Border001.png');
This image doesn't exist on server.
All media files (css, js, img) get a hash prepended to their filename.
Could you add this background-image to the html directly?
Then we can do `{% static 'img/Border001.png' %}`

2019-04-10 23:56 UTC, cyraxjoe commented on static/css/dashboard.css
> +  background-image:url('/static/img/Border001.png');
Sure.

2019-04-11 00:07 UTC, cyraxjoe commented on static/css/dashboard.css
> +  background-image:url('/static/img/Border001.png');
Move it as an in-line style, right after the css import in the dashboard.

2019-04-11 01:50 UTC, czpython approved these changes
Looks good. Thanks!

2019-04-11 01:50 UTC, merged